# Generated by Django 4.2.1 on 2023-06-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swansecurityapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
